name: run-empty-timeslot-hunter

on:
   # schedule:
   #   - cron: '0 0 * * SUN' # At 00:00 on Sunday
   workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: setup python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: execute hunter script # run main.py
        run: python Scrtipts/empty_booking_hunter.py

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          timestamp=$(date +'%Y%m%d%H%M%S')
          branch_name="update-csv-$timestamp"
      
          git checkout -b "$branch_name"
      
          git add <replace_this_csv_filename>
      
          git commit -m "Update CSV file"
      
          git push origin "$branch_name"
      
          git checkout main
          git merge --no-ff "$branch_name"
          git push origin main
      
          # delete the temporary branch
          git branch -d "$branch_name"
          git push origin --delete "$branch_name"
