name: run-empty-timeslot-hunter

on:
  schedule:
    - cron: '0 1 * * SUN' # At 00:00 on Sunday

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: setup python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: execute py script # run main.py
        run: python empty_booking_hunter.py
