name: run-empty-timeslot-hunter

on:
   # schedule:
   #   - cron: '0 0 * * SUN' # At 00:00 on Sunday
   workflow_dispatch

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: setup python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: execute hunter script # run main.py
        run: python Scripts/empty_booking_hunter.py
        
      - name: push
        uses: github-actions-x/commit@v2.9
        with:
           github-token: ${{ secrets.GITHUB_TOKEN }}
           push-branch: 'main'
           commit-message: 'Auto update data'
           force-add: 'true'
           files: data/empty_booking.csv
          
                   
