name: run-booking-scraper

# on:
#   schedule:
#     - cron: '50 14 * * TUE' # At 00:00 on Sunday

on: workflow_dispatch


jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        
      - name: setup python
        uses: actions/setup-python@v5.4.0
        with:
          python-version: '3.13' # install the python version needed

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install selenium
          pip install bs4
          pip install pandas

      - name: execute scraper script # run main.py
        run: python room_timetable_scraper.py

      - name: execute hunter script # run main.py
        run: python empty_booking_hunter.py
